/**
 * Generate otelcol-config.yaml from saved ClickHouse config.
 * Embeds the config template as a JS string so the CLI is self-contained after npm install.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { getConfigDir } from "../config.js";

const CONFIG_TEMPLATE = `# OpenTelemetry Collector config: OTLP + JSONL session logs → ClickHouse
# Generated by: claudicle install collector

receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318

  filelog/sessions:
    include:
      - \${env:HOME}/.claude/projects/**/*.jsonl
    storage: file_storage
    start_at: beginning
    include_file_path: true
    poll_interval: 2s
    max_concurrent_files: 100
    max_batches: 10
    operators:
      - type: json_parser
        parse_from: body
        parse_to: attributes
      - type: time_parser
        if: 'attributes.timestamp != nil'
        parse_from: attributes.timestamp
        layout: "2006-01-02T15:04:05.000Z07:00"
        layout_type: gotime

extensions:
  file_storage:
    directory: \${env:HOME}/.claude-otelcol-storage

processors:
  batch:
    send_batch_size: 5000
    timeout: 5s

  batch/sessions:
    send_batch_size: 500
    timeout: 5s

  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
    spike_limit_mib: 256

  resource/sessions:
    attributes:
      - key: source
        value: claude_jsonl
        action: insert
      - key: service.name
        value: claude-jsonl
        action: insert

  transform/sessions:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["log.file.path"], attributes["log.file.path"])

exporters:
  clickhouse:
    endpoint: {{CLICKHOUSE_TCP_ENDPOINT}}
    username: {{CLICKHOUSE_USER}}
    password: "{{CLICKHOUSE_PASSWORD}}"
    database: {{CLICKHOUSE_DATABASE}}
    create_schema: true
    async_insert: true
    compress: lz4
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    retry_on_failure:
      enabled: true

  debug:
    verbosity: basic

service:
  extensions: [file_storage]
  telemetry:
    logs:
      level: info
  pipelines:
    logs/otel:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    logs/sessions:
      receivers: [filelog/sessions]
      processors: [memory_limiter, resource/sessions, transform/sessions, batch/sessions]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
`;

/**
 * Derive ClickHouse TCP endpoint from HTTP URL.
 * http://host:8123 → tcp://host:9000?dial_timeout=10s
 */
export function deriveClickHouseTcpEndpoint(httpUrl) {
  const url = new URL(httpUrl);
  const host = url.hostname;
  const httpPort = parseInt(url.port || "8123", 10);
  // Convention: TCP port = HTTP port - 8123 + 9000
  const tcpPort = httpPort - 8123 + 9000;
  return `tcp://${host}:${tcpPort}?dial_timeout=10s`;
}

/**
 * Generate collector config YAML with ClickHouse credentials substituted.
 */
export function generateCollectorConfig(chConfig) {
  const tcpEndpoint = deriveClickHouseTcpEndpoint(chConfig.url);

  return CONFIG_TEMPLATE
    .replace("{{CLICKHOUSE_TCP_ENDPOINT}}", tcpEndpoint)
    .replace("{{CLICKHOUSE_USER}}", chConfig.user)
    .replace("{{CLICKHOUSE_PASSWORD}}", chConfig.password)
    .replace("{{CLICKHOUSE_DATABASE}}", chConfig.database);
}

/**
 * Write collector config to ~/.claudicle/collector/otelcol-config.yaml
 */
export function writeCollectorConfig(chConfig) {
  const collectorDir = join(getConfigDir(), "collector");
  mkdirSync(collectorDir, { recursive: true });

  const configPath = join(collectorDir, "otelcol-config.yaml");
  const content = generateCollectorConfig(chConfig);
  writeFileSync(configPath, content, { mode: 0o600 });

  console.log(`Wrote collector config: ${configPath}`);
  return configPath;
}
